server:
  port: 30011

spring:
  application:
    name: app-old-oldlife

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

